---
abstract: 'Provides POSIX-like filesystem semantics in pure Perl'
author:
  - 'Xan Tronix <xan@cpan.org>'
build_requires:
  Test::Builder: '0'
  Test::Deep: '0'
  Test::Exception: '0.26'
  Test::NoWarnings: '0.081'
  Test::Simple: '0.44'
  Try::Tiny: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.94, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Filesys-POSIX
no_index:
  directory:
    - t
    - inc
requires:
  Carp: '0'
resources:
  Type: git
  Url: git://github.com/xantronix/Filesys-POSIX.git
  Web: https://github.com/xantronix/Filesys-POSIX
version: v0.9.16
