--- #YAML:1.0
name:               Filesys-POSIX
version:            0.10.0
abstract:           Provides POSIX filesystem semantics in pure Perl
author:
    - Erin Schoenhals (erin@cpanel.net)
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:              0
    Test::Exception:   0.26
    Test::NoWarnings:  0.081
    Test::Simple:      0.44
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
