---
abstract: 'Provides POSIX filesystem semantics in pure Perl'
author:
  - 'Erin Schoenhals <erin@cpanel.net>'
build_requires:
  Test::Exception: 0.26
  Test::NoWarnings: 0.081
  Test::Simple: 0.44
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Filesys-POSIX
no_index:
  directory:
    - t
    - inc
requires:
  Carp: 0
version: v0.9.9
